name: Deploy to Dev Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 host to known hosts
      run: ssh-keyscan -H 3.110.81.28 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ubuntu@3.110.81.28 -t "cd demo-ci-cd/ && git pull origin main && /home/ubuntu/.nvm/versions/node/v22.14.0/bin/npm install -g pnpm && /home/ubuntu/.nvm/versions/node/v22.14.0/bin/npx pnpm install && /home/ubuntu/.nvm/versions/node/v22.14.0/bin/npx pnpm run build && pm2 restart web-app"
