name: Deploy to Dev Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 host to known hosts
      run: ssh-keyscan -H 3.110.81.28 >> ~/.ssh/known_hosts

    - name: Create symlinks and deploy to EC2
      run: |
        ssh ubuntu@3.110.81.28 -t "
          export NVM_DIR=\"\$HOME/.nvm\" && 
          [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\" && 
          
          sudo ln -sf \"\$NVM_DIR/versions/node/\$(nvm version)/bin/node\" \"/usr/local/bin/node\" && 
          sudo ln -sf \"\$NVM_DIR/versions/node/\$(nvm version)/bin/npm\" \"/usr/local/bin/npm\" && 
          sudo ln -sf \"\$NVM_DIR/versions/node/\$(nvm version)/bin/pm2\" \"/usr/local/bin/pm2\" && 
          
          cd demo-ci-cd/ && 
          git pull origin main && 
          npm install -g pnpm && 
          pnpm install && 
          pnpm run build && 
          pm2 restart web-app
        "